// FILE 5: src/test/java/com/org/java16/RecordsTest.java
package com.org.java16;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Records (Java 16)")
class RecordsTest {

    // ---------------------------------------------------------------------------
    // Record definitions (static nested so they are valid as record declarations)
    // ---------------------------------------------------------------------------

    record Point(int x, int y) {}

    record Range(int min, int max) {
        // Compact constructor — validates invariant
        Range {
            if (min > max) {
                throw new IllegalArgumentException(
                        "min (%d) must be <= max (%d)".formatted(min, max));
            }
        }
    }

    record Person(String name, int age) {
        // Custom constructor with explicit validation
        Person {
            if (name == null || name.isBlank()) {
                throw new IllegalArgumentException("name must not be blank");
            }
            if (age < 0) {
                throw new IllegalArgumentException("age must be non-negative");
            }
        }

        // Custom instance method
        String greeting() {
            return "Hi, I'm %s and I'm %d years old.".formatted(name, age);
        }
    }

    record FullName(String first, String last) {
        // Derived accessor (not a component accessor — just a regular method)
        String full() {
            return first + " " + last;
        }
    }

    record Pair<A, B>(A first, B second) {}

    // ---------------------------------------------------------------------------
    // Auto-generated accessors
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Record auto-generates accessor methods matching component names")
    void autoGeneratedAccessors() {
        Point p = new Point(3, 7);
        assertEquals(3, p.x());
        assertEquals(7, p.y());
    }

    @Test
    @DisplayName("Record accessor returns the exact value passed to the constructor")
    void accessorReturnsConstructorValue() {
        Person person = new Person("Alice", 30);
        assertEquals("Alice", person.name());
        assertEquals(30, person.age());
    }

    // ---------------------------------------------------------------------------
    // equals() and hashCode()
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Two records with identical components are equal")
    void equalRecordsAreEqual() {
        Point p1 = new Point(1, 2);
        Point p2 = new Point(1, 2);
        assertEquals(p1, p2);
    }

    @Test
    @DisplayName("Records with different components are not equal")
    void differentRecordsAreNotEqual() {
        Point p1 = new Point(1, 2);
        Point p2 = new Point(2, 1);
        assertNotEquals(p1, p2);
    }

    @Test
    @DisplayName("Equal records have the same hashCode")
    void equalRecordsHaveSameHashCode() {
        Point p1 = new Point(5, 10);
        Point p2 = new Point(5, 10);
        assertEquals(p1.hashCode(), p2.hashCode());
    }

    @Test
    @DisplayName("Record equals is reflexive")
    void equalsReflexive() {
        Point p = new Point(0, 0);
        assertEquals(p, p);
    }

    @Test
    @DisplayName("Record equals is symmetric")
    void equalsSymmetric() {
        Point p1 = new Point(4, 4);
        Point p2 = new Point(4, 4);
        assertEquals(p1, p2);
        assertEquals(p2, p1);
    }

    // ---------------------------------------------------------------------------
    // toString()
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Record toString contains the class name and component values")
    void toStringContainsClassNameAndValues() {
        Point p = new Point(3, 7);
        String str = p.toString();
        assertTrue(str.contains("Point"), "toString should contain class name");
        assertTrue(str.contains("3"), "toString should contain x value");
        assertTrue(str.contains("7"), "toString should contain y value");
    }

    @Test
    @DisplayName("Record toString matches expected canonical format")
    void toStringCanonicalFormat() {
        Point p = new Point(1, 2);
        assertEquals("Point[x=1, y=2]", p.toString());
    }

    // ---------------------------------------------------------------------------
    // Compact constructor validation
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Compact constructor validates invariant and accepts valid input")
    void compactConstructorAcceptsValidRange() {
        Range r = new Range(1, 10);
        assertEquals(1, r.min());
        assertEquals(10, r.max());
    }

    @Test
    @DisplayName("Compact constructor throws when invariant is violated")
    void compactConstructorRejectsInvalidRange() {
        IllegalArgumentException ex = assertThrows(
                IllegalArgumentException.class,
                () -> new Range(10, 1));
        assertTrue(ex.getMessage().contains("min"), "Exception message should mention 'min'");
    }

    @Test
    @DisplayName("Compact constructor allows equal min and max (single-value range)")
    void compactConstructorAllowsEqualBounds() {
        assertDoesNotThrow(() -> new Range(5, 5));
    }

    // ---------------------------------------------------------------------------
    // Custom methods on records
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Custom instance method on record works correctly")
    void customInstanceMethod() {
        Person alice = new Person("Alice", 28);
        assertEquals("Hi, I'm Alice and I'm 28 years old.", alice.greeting());
    }

    @Test
    @DisplayName("Custom derived method on record computes from component accessors")
    void customDerivedMethod() {
        FullName name = new FullName("John", "Doe");
        assertEquals("John Doe", name.full());
    }

    // ---------------------------------------------------------------------------
    // Records are implicitly final
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Record class is final and cannot be extended (checked at compile time)")
    void recordIsFinal() {
        // Records are final by definition. This is a runtime check of the modifier.
        assertTrue(java.lang.reflect.Modifier.isFinal(Point.class.getModifiers()));
    }

    // ---------------------------------------------------------------------------
    // Generic records
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Generic record holds typed components correctly")
    void genericRecord() {
        Pair<String, Integer> pair = new Pair<>("hello", 42);
        assertEquals("hello", pair.first());
        assertEquals(42, pair.second());
    }

    @Test
    @DisplayName("Generic records with same components are equal")
    void genericRecordEquality() {
        Pair<String, Integer> p1 = new Pair<>("a", 1);
        Pair<String, Integer> p2 = new Pair<>("a", 1);
        assertEquals(p1, p2);
    }

    // ---------------------------------------------------------------------------
    // Null components
    // ---------------------------------------------------------------------------

    @Test
    @DisplayName("Record component can hold null when not validated")
    void recordWithNullComponent() {
        FullName name = new FullName(null, "Doe");
        assertNull(name.first());
        assertEquals("Doe", name.last());
    }

    @Test
    @DisplayName("Record custom constructor rejects null name")
    void customConstructorRejectsNull() {
        assertThrows(IllegalArgumentException.class, () -> new Person(null, 25));
    }
}
